name: Build

on: [push, pull_request]

env:
  CIBW_BEFORE_BUILD: "cd scripts && bash install_cmake.bash"

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.4.1
        
    - name: Install cmake
      run: |
        wget https://github.com/Kitware/CMake/releases/download/v3.17.0/cmake-3.17.0-Linux-x86_64.tar.gz
        tar -zxf cmake-3.17.0-Linux-x86_64.tar.gz
        cd cmake-3.17.0-Linux-x86_64
        export PATH=$PWD/bin:$PATH
        echo ${PATH}
        cd ..
   
    - name: Build wheel
      run: |
        python -m cibuildwheel --output-dir wheelhouse
    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse
